name: OZProject Java CI with Maven

on:
  push:
    branches: [ "master" ]

jobs:
  OzPro:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Install Allure
      run: |
        Invoke-WebRequest -Uri https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.10.0/allure-commandline-2.10.0.zip -OutFile C:\allure-commandline-2.10.0.zip
        PowerShell -Command "Expand-Archive -Path C:\allure-commandline-2.10.0.zip -DestinationPath C:\"
        Remove-Item C:\allure-commandline-2.10.0.zip
      env:
        ALLURE_HOME: C:\allure-2.10.0
    - name: Run tests and generate Allure report
      run: |
        mvn -Dbrowser=chrome -Denvironment=dev clean test
        & ${env:ALLURE_HOME}\bin\allure generate --clean target/allure-results --report-dir allure-report
    - name: Upload Allure report
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: allure-report
