name: OZProject Java CI with Maven

on:
  push:
    branches: [ "master" ]

jobs:
  OzPro:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Install Allure
      run: |
        Invoke-WebRequest -Uri https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.10.0/allure-commandline-2.10.0.tgz
        mkdir allure
        tar -zxf allure-2.10.0.tgz -C allure --strip-components 1
        rm allure-2.10.0.tgz
    - name: Run tests and generate Allure report
      run: |
        mvn -Dbrowser=chrome -Denvironment=dev clean test
        allure/bin/allure generate --clean allure-results --report-dir allure-report
    - name: Upload Allure report
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: allure-report
